version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis_broker
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      INPUT_FOLDER: ${INPUT_FOLDER}
      OUTPUT_FOLDER: ${OUTPUT_FOLDER}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks.celery_app worker --loglevel=info
    volumes:
      - ./data:/app/data
    environment:
      INPUT_FOLDER: ${INPUT_FOLDER}
      OUTPUT_FOLDER: ${OUTPUT_FOLDER}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
