version: '3.9'  # optional, can remove as per warning

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: fastapi
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./MISUMI_Home:/app/MISUMI_Home
    
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./MISUMI_Home:/app/MISUMI_Home
    depends_on:
      - redis
